version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django_files
      POSTGRES_PASSWORD: django_files
      POSTGRES_DB: django_files
    restart: always
    ports:
    - "5432:5432"

  frontend:
    build: ../frontend_react/.
    volumes:
      - frontend:/app/build
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ../django_files/django_static/:/usr/share/nginx/html/django_static/
      - ../django_files/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:  
  frontend: